#ifndef DATA_H
#define DATA_H

#define DEFAULT_FOREGROUND 7

#define APPLICATION_NAME "New Age"
#define FILE_PNGS_PATH "pngs\\" // PUT THE PATH TO YOUR PNG FOLDER INBETWEEN THESE QUOATION MARKS

#define COMMENT_MARKER '/'
#define VARIABLE_MARKER '#'
#define CATEGORY_MARKER '%'
#define EXERCISE_MARKER '$'
#define DESCRIPTION_MARKER '"'
#define START_MARKER '~' // FEATURE NO LONGER IN USE
#define NO_DISPLAY_MARKER '&' // FEATURE NO LONGER IN USE
#define CONTROL_MARKER '@' // FEATURE NO LONGER IN USE

#endif
