#ifndef DATA_H
#define DATA_H

#define DEFAULT_FOREGROUND 7

#define APPLICATION_NAME "New Age"
#define FILE_PATH "ex.newage" // PUT THE PATH TO YOUR .newage FILE INBETWEEN THESE QUOATION MARKS
#define FILE_PNGS_PATH "pngs\\" // PUT THE PATH TO YOUR PNG FOLDER INBETWEEN THESE QUOATION MARKS

#define DEFAULT_FREESTYLE 'N'
#define DEFAULT_SETS 1
#define DEFAULT_REPS 15
#define DEFAULT_HOLD 20
#define DEFAULT_AHOLD 3

#define COMMENT_MARKER '/'
#define VARIABLE_MARKER '#'
#define CATEGORY_MARKER '%'
#define EXERCISE_MARKER '$'
#define START_MARKER '~' // FEATURE NO LONGER IN USE
#define NO_DISPLAY_MARKER '&' // FEATURE NO LONGER IN USE
#define CONTROL_MARKER '@' // FEATURE NO LONGER IN USE

#endif
